### ISSUE TITLE
Assets/Scripts/Animation

### ISSUE THREAD

**Issue by EthanNichols** [C0dedSurvivor/TRPG#2]
In all of your animation scripts that are unused/useless `using` decelerations. They should be cleaned up.

### Inheritence
This could probably be in the Questionable section...
All the `FlatSpeedMovementAnim.cs` class inherit from `DecceleratingMovmentAnim.cs` which seems redundant. Since FlatSpeedMovementAnim doesn't override any DecceleratingMovementAnim functions/properties. You could add a class called `MovementAnim.cs` Which is inherited by FlatSpeedMovementAnim and DecceleratingMovementAnim. Just seems weird to inherit from a decelerating class to a flatspeed class. The same goes for RotationAnim and ScaleAnim.

### Formatting / Grammer
`DecceleratingRotationAnim.cs` doesn't follow the format of other animation script. There should be a space between the `using` declarations and the class deceleration

`FlatSpeedRotationAnim.cs` class doesn't have an access modifier.
`DecceleratingRotationAnim.cs` class doesn't have an access modifier.
`FlatSpeedMovementAnim.cs` class doesn't have an access modifier.
`DecceleratingMovementAnim.cs` class doesn't have an access modifier.

`Deccelerate` is spelled Decelerate. There's an extra `C` in your spelling.

As a side note. I always try to do the key control (`Ctrl` + `K` + `D`) which usually correctly formats your code.

### Suggestion(s):
Comment your animation scripts.

For example: It seems like `StepAnimation()` should be called in an update function. But it isn't clear that that is where/how it should be used.

### Questionable
in `FlatSpeedMovementAnim.cs` there is a property called `Difference` not sure what you're formatting style is.
I personally like the format:
```
public Vector3 Difference
{
	get
	{
		return initialPosition - finalPosition;
	}
}
```
Another optional format is:
```
public Vector3 Difference => initialPosition - finalPosition;
```
Not really a suggestion or formatting issue. Just a note that your should keep your formatting clearly defined throughout the project. So if this is how all of your properties are. Then there's no issue.

There a couple constructor functions that call the inherited base function. Since a lot of these constructor are long, for readability you might want to shorten the line length.
`public FlatSpeedMovementAnim(GameObject target, float speed, Vector3 initialPos, Vector3 finalPos, bool concurrent = false) : base(target, speed, finalPos, concurrent)`
Could be:
```
public FlatSpeedMovementAnim(GameObject target, float speed, Vector3 initialPos, Vector3 finalPos, bool concurrent = false
	: base(target, speed, finalPos, concurrent)
{
	...
}	
```
Alternatively
```
public FlatSpeedMovementAnim(GameObject target,
	float speed,
	Vector3 initialPos,
	Vector3 finalPos,
	bool concurrent = false)
	: base(target, speed, finalPos, concurrent)
{
	...
}			
```

**Comment by Jacob-Brosler** [comment]
Fixed
